version: '3.7'
services:
  vault:
    image: hashicorp/vault
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root-token-demo"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
  mongodb:
    image: mongo:7.0.4-rc0-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=changeme
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
volumes:
    mongodb: